# Generated by Django 3.0.4 on 2020-03-15 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empno', models.IntegerField()),
                ('empname', models.CharField(max_length=60)),
                ('empsal', models.IntegerField()),
                ('empaddr', models.CharField(max_length=60)),
            ],
        ),
    ]
