# Generated by Django 3.0.4 on 2020-04-03 11:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
