# Generated by Django 3.0.4 on 2020-04-07 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_atm_pan_passport_voterid'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAdhar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('uid', models.IntegerField()),
            ],
        ),
    ]
