# Generated by Django 3.0.4 on 2020-04-09 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='cnum',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
